// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	batch "github.com/a-kataev/go-influxdb-writer/internal/batch"
	mock "github.com/stretchr/testify/mock"
)

// Batch is an autogenerated mock type for the Batch type
type Batch struct {
	mock.Mock
}

// Reader provides a mock function with given fields:
func (_m *Batch) Reader() *batch.BatchReader {
	ret := _m.Called()

	var r0 *batch.BatchReader
	if rf, ok := ret.Get(0).(func() *batch.BatchReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batch.BatchReader)
		}
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *Batch) Reset() {
	_m.Called()
}

// Write provides a mock function with given fields: e
func (_m *Batch) Write(e []byte) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
