// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/a-kataev/go-influxdb-writer/internal/client"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, reader
func (_m *Client) Send(ctx context.Context, reader io.Reader) (*client.ClientResponse, error) {
	ret := _m.Called(ctx, reader)

	var r0 *client.ClientResponse
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) *client.ClientResponse); ok {
		r0 = rf(ctx, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
